### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by ssine** [padlocal/padlocal-client-ts#4]
What may be the issue?

```
23:44:40 INFO
      ============================================================
                    Welcome to padlocal-client-ts !
                           version: 0.4.1
      ============================================================

start login
start login with type:  1
(node:1018806) UnhandledPromiseRejectionWarning: VError: [tid:8b344ee6] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:8b344ee6] login failed                                                   
    at Request._failAllPendingRequest (/home/sine/project/moments-dump/node_modules/padlocal-client-ts/src/Request.ts:334:15)                                                                                         
    at ClientDuplexStreamImpl.<anonymous> (/home/sine/project/moments-dump/node_modules/padlocal-client-ts/src/Request.ts:82:12)                                                                                      
    at ClientDuplexStreamImpl.emit (events.js:315:20)
    at ClientDuplexStreamImpl.EventEmitter.emit (domain.js:467:12)
    at Object.onReceiveStatus (/home/sine/project/moments-dump/node_modules/@grpc/grpc-js/src/client.ts:673:18)                                                                                                       
    at Object.onReceiveStatus (/home/sine/project/moments-dump/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)                                                                                          
    at /home/sine/project/moments-dump/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1018806) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1018806) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.        
00:13:13 ERR [PadLocalClient] error while syncing onpush: VError: [tid:0904d2db] request has been cancelled for reason: CLIENT_ERROR: [tid:0904d2db] Exception while handling wechat request: socket hang up          
    at Request._failAllPendingRequest (/home/sine/project/moments-dump/node_modules/padlocal-client-ts/src/Request.ts:334:15)                                                                                         
    at Request.error (/home/sine/project/moments-dump/node_modules/padlocal-client-ts/src/Request.ts:347:10)                                                                                                          
    at Request.<anonymous> (/home/sine/project/moments-dump/node_modules/padlocal-client-ts/src/Request.ts:221:16)                                                                                                    
    at Generator.throw (<anonymous>)
    at rejected (/home/sine/project/moments-dump/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by ssine** [comment]
Seems to be a server side issue, working by now
